# Generated by Django 4.0.5 on 2022-06-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='pric',
            new_name='price',
        ),
    ]
